---
- name: update packages
  become: yes
  apt:
    update_cache: true

- name: install docker
  become: yes
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" -y
    apt-cache policy docker-ce
    sudo apt install docker-ce -y
    sudo systemctl status docker > docker_status.log 2>&1

- name: Install docker compose
  become: yes
  shell: |
    sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    docker-compose --version

# - name: Download airflow docker compose file
#   get_url:
#     url: https://airflow.apache.org/docs/apache-airflow/2.8.0/docker-compose.yaml
#     dest: ~

- name: download airflow docker compose file
  become: yes
  shell: |
    curl -LfO 'https://airflow.apache.org/docs/apache-airflow/2.8.0/docker-compose.yaml'
    mkdir -p wo/dags workflow/logs workflow/plugins workflow/config
    echo -e "AIRFLOW_UID=$(id -u)" > .env
    sudo docker compose up airflow-init
    sudo docker compose up
    
- name: postgres and pg services
  docker_compose:
    project_name: db
    definition:
      services:
        pgdatabase:
          image: postgres:13
          environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin_password
            - POSTGRES_DB=newyork_taxi
          # volumes:
          ports:
            - "5432:5432"

        pgadmin:
          image: dpage/pgadmin4
          environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin_password
          ports:
            - "8090:80"

- name: Create and start services
  docker_compose:
    project_src: db
  register: output
  