version: 2.1

commands:
  destroy-infra:
    description: Destroy infrastructure on failure.
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            cd circleci/test_ec2
            terraform destroy --auto-approve

  install-ansible:
    description: Install Ansible
    steps:
      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install ansible -y

  install-terraform:
    description: Install Terraform
    steps:
      - run:
          name: Install Terraform
          command: |
            wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo apt-get update && sudo apt-get install -y gnupg software-properties-commonsudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt update && sudo apt install terraform -y


  