services:
  pgdatabase:
    image: postgres:13
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_DB=newyork_taxi
    # volumes:
    #   - "/home/ubuntu/Data-Engineering-Zoomcamp/newyork-db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin_password
    ports:
      - "8090:80"